In [1]:
import numpy as np
import pandas as pd

# Data Import

In [2]:
df= pd.read_json('assign_chubb_engineering.json')

In [3]:
df=df.transpose()
df

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001
...,...,...,...,...,...,...,...
babu it jobs,None,{'company_name': {'Tech Mahindra': {'count': 1...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001
capital honda service centre,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001
systems plus llc,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001
gemini traze rfid pvt ltd,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001
radiate e-services pvt. ltd.,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001

# Null Values in each column

In [4]:
df.isna().sum()

company_uuid                                        12449
companies_they_hire_from                                0
employees                                               0
companies_where_their_ex_employees_work                 0
is_score_calculated                                     0
Department_Tier-1_College_Density_Score                 0
Department_Tier-1_College_Freshers_Density_Score        0
dtype: int64

#  To find list of companies where hiring companies hire from

In [5]:
df = pd.concat([df, df["companies_they_hire_from"].apply(pd.Series)], axis=1)

In [6]:
df=df.rename ({'count':'count_A'},axis=1)
df=df.rename ({'company_name':'company_name_A'},axis=1)
df

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score,company_name_A,count_A
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'L&T Technology Services Ltd.': {'count': 1, ...",1
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464,"{'HCL Technologies': {'count': 86, 'data': [{'...",4019
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714,"{'Tata Consultancy Services': {'count': 297, '...",1614
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001,"{'Ultra-Scan Corporation': {'count': 3, 'data'...",6
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001,"{'Wipro Technologies': {'count': 113, 'data': ...",1102
...,...,...,...,...,...,...,...,...,...
babu it jobs,None,{'company_name': {'Tech Mahindra': {'count': 1...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'Tech Mahindra': {'count': 1, 'data': [{'prev...",1
capital honda service centre,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0
systems plus llc,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0
gemini traze rfid pvt ltd,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0
radiate e-services pvt. ltd.,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0

In [7]:
df["companies_they_hire_from-B"] = list(df["company_name_A"].keys())

In [8]:
df

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score,company_name_A,count_A,companies_they_hire_from-B
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'L&T Technology Services Ltd.': {'count': 1, ...",1,altran technologies india pvt ltd
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464,"{'HCL Technologies': {'count': 86, 'data': [{'...",4019,L&T Technology Services Ltd.
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714,"{'Tata Consultancy Services': {'count': 297, '...",1614,Amdocs
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001,"{'Ultra-Scan Corporation': {'count': 3, 'data'...",6,Xperia
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001,"{'Wipro Technologies': {'count': 113, 'data': ...",1102,Ultra-Scan Corporation
...,...,...,...,...,...,...,...,...,...,...
babu it jobs,None,{'company_name': {'Tech Mahindra': {'count': 1...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'Tech Mahindra': {'count': 1, 'data': [{'prev...",1,babu it jobs
capital honda service centre,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,capital honda service centre
systems plus llc,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,systems plus llc
gemini traze rfid pvt ltd,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,gemini traze rfid pvt ltd
radiate e-services pvt. ltd.,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,radiate e-services pvt. ltd.

# Classification based on No. of Employees

In [9]:
df = pd.concat([df, df["employees"].apply(pd.Series)], axis=1)

In [10]:
df=df.drop('employees_uuid',axis=1)
df=df.drop('freshers_uuid',axis=1)
df['total_employees']=df['count']+df['freshers_count']
df=df.drop('count',axis=1)
df=df.drop('freshers_count',axis=1)

In [11]:
df = pd.concat([df, df["from_iit"].apply(pd.Series)], axis=1)
df=df.drop('employees_uuid',axis=1)
df=df.drop('freshers_uuid',axis=1)
df['total_employees']=df['total_employees']+df['count']+df['freshers_count']
df=df.drop('count',axis=1)
df=df.drop('freshers_count',axis=1)

In [12]:
df=df.drop('from_iit',axis=1)
df = pd.concat([df, df["from_bits"].apply(pd.Series)], axis=1)
df=df.drop('employees_uuid',axis=1)
df=df.drop('freshers_uuid',axis=1)
df['total_employees']=df['total_employees']+df['count']+df['freshers_count']
df=df.drop('count',axis=1)
df=df.drop('freshers_count',axis=1)
df=df.drop('from_bits',axis=1)

In [13]:
df = pd.concat([df, df["from_nit"].apply(pd.Series)], axis=1)
df=df.drop('employees_uuid',axis=1)
df=df.drop('freshers_uuid',axis=1)
df['total_employees']=df['total_employees']+df['count']+df['freshers_count']
df=df.drop('count',axis=1)
df=df.drop('freshers_count',axis=1)
df=df.drop('from_nit',axis=1)

In [14]:
df

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score,company_name_A,count_A,companies_they_hire_from-B,total_employees
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'L&T Technology Services Ltd.': {'count': 1, ...",1,altran technologies india pvt ltd,1
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464,"{'HCL Technologies': {'count': 86, 'data': [{'...",4019,L&T Technology Services Ltd.,9086
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714,"{'Tata Consultancy Services': {'count': 297, '...",1614,Amdocs,1749
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001,"{'Ultra-Scan Corporation': {'count': 3, 'data'...",6,Xperia,6
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001,"{'Wipro Technologies': {'count': 113, 'data': ...",1102,Ultra-Scan Corporation,1230
...,...,...,...,...,...,...,...,...,...,...,...
babu it jobs,None,{'company_name': {'Tech Mahindra': {'count': 1...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'Tech Mahindra': {'count': 1, 'data': [{'prev...",1,babu it jobs,1
capital honda service centre,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,capital honda service centre,0
systems plus llc,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,systems plus llc,0
gemini traze rfid pvt ltd,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,gemini traze rfid pvt ltd,0
radiate e-services pvt. ltd.,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,radiate e-services pvt. ltd.,0

# Employee Category Based on employee no.

In [15]:
def Employee_category(value):
    if value in range(1,10):
        return '1'
    if value in range(11,50):
        return '2'
    elif value in range(51,100):
        return '3'
    elif value in range(101,250):
        return '4'
    elif value in range(251,500):
        return '5'
    elif value in range(510,1000):
        return '6'
    elif value in range(1001,5000):
        return '7'
    elif value in range(5001,10000):
        return '8'
    elif value > 10000:
        return '9'
    
df['Employee_category'] = df['total_employees'].map(Employee_category)
df

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score,company_name_A,count_A,companies_they_hire_from-B,total_employees,Employee_category
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'L&T Technology Services Ltd.': {'count': 1, ...",1,altran technologies india pvt ltd,1,1
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464,"{'HCL Technologies': {'count': 86, 'data': [{'...",4019,L&T Technology Services Ltd.,9086,8
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714,"{'Tata Consultancy Services': {'count': 297, '...",1614,Amdocs,1749,7
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001,"{'Ultra-Scan Corporation': {'count': 3, 'data'...",6,Xperia,6,1
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001,"{'Wipro Technologies': {'count': 113, 'data': ...",1102,Ultra-Scan Corporation,1230,7
...,...,...,...,...,...,...,...,...,...,...,...,...
babu it jobs,None,{'company_name': {'Tech Mahindra': {'count': 1...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'Tech Mahindra': {'count': 1, 'data': [{'prev...",1,babu it jobs,1,1
capital honda service centre,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,capital honda service centre,0,None
systems plus llc,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,systems plus llc,0,None
gemini traze rfid pvt ltd,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,gemini traze rfid pvt ltd,0,None
radiate e-services pvt. ltd.,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,radiate e-services pvt. ltd.,0,None


## No. of companies for each category

In [16]:
df['Employee_category'].value_counts()

1    24148
2     1458
3      275
4      221
5       71
6       36
7       31
9       10
8        3
Name: Employee_category, dtype: int64

In [17]:
df.head(5)

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score,company_name_A,count_A,companies_they_hire_from-B,total_employees,Employee_category
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'L&T Technology Services Ltd.': {'count': 1, ...",1,altran technologies india pvt ltd,1,1
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464,"{'HCL Technologies': {'count': 86, 'data': [{'...",4019,L&T Technology Services Ltd.,9086,8
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714,"{'Tata Consultancy Services': {'count': 297, '...",1614,Amdocs,1749,7
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001,"{'Ultra-Scan Corporation': {'count': 3, 'data'...",6,Xperia,6,1
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001,"{'Wipro Technologies': {'count': 113, 'data': ...",1102,Ultra-Scan Corporation,1230,7

## Tier-1 strength

In [18]:
df['tier1_strength']=df['Department_Tier-1_College_Density_Score']+df['Department_Tier-1_College_Freshers_Density_Score']
df['tier1_strength']=(df['tier1_strength']*df['total_employees'])/100
df

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score,company_name_A,count_A,companies_they_hire_from-B,total_employees,Employee_category,tier1_strength
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'L&T Technology Services Ltd.': {'count': 1, ...",1,altran technologies india pvt ltd,1,1,0.0
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464,"{'HCL Technologies': {'count': 86, 'data': [{'...",4019,L&T Technology Services Ltd.,9086,8,0.830428
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714,"{'Tata Consultancy Services': {'count': 297, '...",1614,Amdocs,1749,7,0.716642
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001,"{'Ultra-Scan Corporation': {'count': 3, 'data'...",6,Xperia,6,1,0.000001
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001,"{'Wipro Technologies': {'count': 113, 'data': ...",1102,Ultra-Scan Corporation,1230,7,0.88486
...,...,...,...,...,...,...,...,...,...,...,...,...,...
babu it jobs,None,{'company_name': {'Tech Mahindra': {'count': 1...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001,"{'Tech Mahindra': {'count': 1, 'data': [{'prev...",1,babu it jobs,1,1,0.0
capital honda service centre,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,capital honda service centre,0,None,0.0
systems plus llc,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,systems plus llc,0,None,0.0
gemini traze rfid pvt ltd,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,gemini traze rfid pvt ltd,0,None,0.0
radiate e-services pvt. ltd.,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001,{},0,radiate e-services pvt. ltd.,0,None,0.0

In [19]:
np.mean(df['tier1_strength'])

0.0021622666996243827

In [20]:
np.median(df['tier1_strength'])

0.0

## Top 5 and bottom 5

In [21]:
df['tier1_strength']=df['tier1_strength'].astype(float)

In [23]:
df['tier1_strength'].nlargest(n=5)

Wipro Technologies                        8.259639
BigMachines                               7.785726
Tata Consultancy Services                 7.220439
Mastercard Loyalty Solutions Australia    5.154724
Infosys                                   4.766612
Name: tier1_strength, dtype: float64

In [24]:
df['tier1_strength'].nsmallest(n=5)

mts technologies ltd                  0.0
pronto consulting services pvt ltd    0.0
Bull Academy and IT Services          0.0
indus projects ltd panipat            0.0
IDS Next                              0.0
Name: tier1_strength, dtype: float64

## Data Exporting

In [31]:
df.to_excel('category_k.xlsx')